### ISSUE TITLE
Update UI copy to fit Public Domain

### ISSUE THREAD

**Issue by jessbeutler** [publicdomainmap/issues#22]
Need to update all text on the TM UI from humanitarian to Public Domain branding. 

Text to update includes:

**Home Page**

- [ ] MAP FOR PEOPLE IN NEED
Join a global community that is mapping the places most vulnerable to disaster and poverty in order to support humanitarian aid and sustainable development across the world.
- [ ] Each year, disasters around the world kill nearly 100,000 and affect or displace 200 million people. Mapping can help change this.
- [ ] Organizations use Tasking Manager to create mapping projects for areas around the world where data is needed to help save or improve lives.
- [ ] Humanitarian organizations use the map data to plan for disaster response and other life saving activities.
- [ ] Trusted global organizations use Tasking Manager to get the map data they need to reach those in need.
- [ ] YOU CAN MAKE A DIFFERENCE
"In the early days of the Cyclone Idai response, IFRC was looking for detailed maps to get a sense of the scale of the flooding, which were also used for search and rescue operations. Later on, we had requests to identify where certain buildings, such as health centres or hospitals, were located so our health team could assess the damage and medical needs of patients.
Lauren Bateman, Remote Coordinator for the IFRC Information Management Team for Cyclone Idai".
- [ ] Tasking Manager is a platform where individuals can team up for mapping in OpenStreetMap

**About**

- [ ] Every day, a global community works tirelessly behind the scenes to make the more complete map of the world. The resulting work is Open Data and can be used by anyone. Universal access to geospatial information is heavily changing how people use maps and what they build with them.

A separate issue will be created for the "Learn" section to determine if there's any different materials/links needed.

**Comment by DeraldDudley** [comment]
Thoughts on this?

PDTM HOME PAGE
TOP BANNER

PUBLIC DOMAIN MAPPING
The Public Domain Mapping community is dedicated to collecting and publishing geospatial data that are free to copy, share, alter, and republish.  Eliminating data use barriers liberates government agencies and private industry to consume, analyze, enhance, and distribute data to better inform policy decisions.

USE STATISTICS
Many government agencies and private companies are unwilling to accept the legal risk of using data not explicitly placed in the public domain.  Removing these restrictions fosters data sharing, the creation of knowledge, and cultivates understanding.  Let us use our knowledge and understanding to improve our world.
The Public Domain Tasking Manager (PDTM) presents mapping needs and leverages the power of crowd sourcing to collect geospatial data.  The data are quality checked and then released into the public domain. 

WHO USES THE MAPS?
Trusted global organizations use Public Domain Tasking Manager to get the map data they need to reach those in need.
List Government Agencies and Private Organizations - Need Logos


YOU CAN MAKE A DIFFERENCE
"We need a quote”
Derald Dudley, Transportation Theme Lead, NSDI, USDOT - 

FOOTER
Tasking Manager is a platform where individuals can team up for mapping in a public domain version of OpenStreetMap.

About
Every day, a global community works tirelessly behind the scenes to make the more complete map of the world. The resulting work is Open Data and can be used by anyone. Universal access to geospatial information is heavily changing how people use maps and what they build with them.

**Comment by jessbeutler** [comment]
Thanks, Derald! I did some minor rearranging/modifying to better fit the word counts used on other Tasking Managers. How do you feel about this?

> TOP BANNER
>  
> MAP FOR PUBLIC GOOD 
> Join the Public Domain Map community in improving, collecting and publishing open geospatial data used by government agencies, private industry, and nonprofits to better inform policy decisions.
>  
> USE STATISTICS
> The Public Domain Mapping community is dedicated to collecting and publishing quality geospatial data that are free to copy, share, alter, and republish.
>  
> The Public Domain Tasking Manager presents mapping needs and leverages the power of crowd sourcing to collect geospatial data.  The data are quality checked and then released into the Public Domain.
>  
> WHO USES THE MAPS?
> Trusted agencies and organizations use the Public Domain Tasking Manager to get the map data they need to reach those in need.
> List Government Agencies and Private Organizations - Need Logos
>  
>  
> YOU CAN MAKE A DIFFERENCE
> "Many government agencies and private companies are unwilling to accept the legal risk of using data not explicitly placed in the public domain.  Removing these restrictions fosters data sharing, the creation of knowledge, and cultivates understanding.”
> Derald Dudley, Transportation Theme Lead, NSDI, USDOT -
>  
> FOOTER
> Tasking Manager is a platform where individuals can team up for mapping in a public domain version of OpenStreetMap. Let us use our knowledge and understanding to improve our world.
>  
> 
> ABOUT
> Every day, a global community works tirelessly behind the scenes to make a more complete map of the world. The resulting work is Open Data and can be used by anyone. Universal access to geospatial information is heavily changing how people use maps and what they build with them.
> 
> The purpose of the Tasking Manager is to divide a large mapping project into smaller tasks that can be completed rapidly and collaboratively, with many people contributing to a collective project goal. The tool shows what needs to be mapped, which areas need to be reviewed and validated for quality assurance and which areas are completed.
> 
> This approach allows the distribution of tasks to many individual mappers. It also allows monitoring of project progress and helps to improve the consistency of the mapping (e.g. elements to cover, specific tags to use, etc.)
> 
> All contributions remain in the public domain, which allows the original government public domain datasets to accept edits from users and allows the edits to be applied to OpenStreetMap. OpenStreetMap is the community-driven free and editable map of the world, supported by the not-for-profit OpenStreetMap Foundation.
> 
> Read more on the OSM Wiki or join the discussion with your local OSM community.
> 
> Access the Tasking Manager Sustainability Model FAQs for services and support information.




It would be good to provide a link to further information on what Public Domain is in this text. Is there a resource at a .gov address that we can use? Otherwise we can link to wikipedia or Creative Commons.

**Comment by DeraldDudley** [comment]
It looks good.  Appreciate your softening it too. Should we get more eyes on it?

**Comment by GDMatthews** [comment]
Thanks for this text. I've added a few edits for consideration. See bolded below and the comment at the bottom about referencing a definition. Whether you integrate the changes or not, I think this is ready to publish.

TOP BANNER
MAP FOR PUBLIC GOOD
Join the Public Domain Map community in improving, collecting, and publishing open geospatial data **that can be** used by government agencies, private industry, and nonprofits to **support products and services and** to better inform policy decisions.
USE STATISTICS
The Public Domain Mapping community is dedicated to collecting and publishing quality geospatial data that are **owned by the public, and** free to copy, share, alter, and republish.
The Public Domain Tasking Manager presents mapping needs and leverages the power of crowd sourcing to collect geospatial data. The data are quality checked and then released into the Public Domain.
WHO USES THE MAPS? **WHO USES THE DATA?**
Trusted agencies and organizations use the Public Domain Tasking Manager to get the map data they need to reach those in need.
List Government Agencies and Private Organizations - Need Logos
YOU CAN MAKE A DIFFERENCE
"Many government agencies and private companies are unwilling to accept the legal risk of using data not explicitly placed in the public domain. Removing these restrictions fosters data sharing, the creation of knowledge, and cultivates understanding.”
Derald Dudley, Transportation Theme Lead, NSDI, USDOT -
FOOTER
Tasking Manager is a platform where individuals can team up for mapping in a public domain version of OpenStreetMap. Let us use our knowledge and understanding to improve our world.
ABOUT
Every day, a global community works tirelessly behind the scenes to make a more complete map of the world. The resulting work is Open Data, **free from copyright, trademark or patents**, and can be used by anyone. Universal access to geospatial information is heavily changing how people use maps and what they build with them.
The purpose of the Tasking Manager is to divide a large mapping project into smaller tasks that can be completed rapidly and collaboratively, with many people contributing to a collective project goal. The tool shows what needs to be mapped, which areas need to be reviewed and validated for quality assurance and which areas are completed.
This approach allows the distribution of tasks to many individual mappers. It also allows monitoring of project progress and helps to improve the consistency of the mapping (e.g. elements to cover, specific tags to use, etc.)
All contributions remain in the public domain, which allows the original government public domain datasets to accept edits from users and allows the edits to be applied to OpenStreetMap. OpenStreetMap is the community-driven free and editable map of the world, supported by the not-for-profit OpenStreetMap Foundation.
Read more on the OSM Wiki or join the discussion with your local OSM community.
Access the Tasking Manager Sustainability Model FAQs for services and support information.
It would be good to provide a link to further information on what Public Domain is in this text. Is there a resource at a .gov address that we can use? Otherwise we can link to Wikipedia or Creative Commons.

**I suggest a reference can be made "for more information on the OSM PD project see : https://www.openstreetmap.us/2021/05/gov-committee-pilot/**
**I’ve never seen a definition of public domain on gov websites. I usually reference Public domain - Wikipedia when providing definitions.**

**Comment by mvexel** [comment]
@jimmyrocks what I see on [tm.publicdomainmap](https://tm.publicdomainmap.org) does not correspond with what I see in https://github.com/publicdomainmap/tasking-manager/blob/4d16d4ce3f2fca7ea7910a04af78b5d0eabe9245/frontend/src/components/homepage/messages.js#L9

Did someone perhaps already update some of these strings and didn't update the ticket?

**Comment by jessbeutler** [comment]
@mayashap updated those but they have not been pushed to production. Current project status reflects this (but let me know if there's a better way to show this)

![image](https://user-images.githubusercontent.com/36767434/171465845-3dfffe37-ab44-494b-a9ec-bcc54c086ef8.png)

**Comment by quincylvania** [comment]
Superseded by use of OSMSU tasking manager.
